[custom]
;========================================================
; ACL4SSR Lite + blackmatrix7 精细规则混合版
; 适用于：
; OpenClash / Clash Meta / Mihomo
; OpenWrt 旁路由
; Fake-IP + TUN
; SmartDNS / Dnsmasq
;========================================================

;========================
; 规则集
;========================

; 局域网
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,clash-domain:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_direct_domain.yaml,28800
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_direct_ip.yaml,28800

;国内游戏域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
;Steam 下载 CDN 直连
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN_Classical.yaml,28800
;各大游戏平台下载域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
;BT Tracker 相关域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker

; 广告拦截
;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛑 全球拦截,clash-domain:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_reject_domain.yaml,28800
ruleset=🛑 全球拦截,clash-classic:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_reject_ip.yaml,28800

; Google 国内服务
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

; Steam 国区
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

; AI 平台
ruleset=💬 AI平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI平台,[]GEOSITE,openai
ruleset=💬 AI平台,[]GEOSITE,onedrive
ruleset=💬 AI平台,[]GEOSITE,bing
ruleset=💬 AI平台,[]GEOSITE,category-ai-!cn

; GitHub
ruleset=🐙 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list

; 微软
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

; Apple
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

; Telegram
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📲 电报信息,[]GEOIP,telegram,no-resolve

; Talkatone
ruleset=📞 Talkatone,[]GEOSITE,talkatone
;ruleset=Talkatone,https://raw.githubusercontent.com/LOWERTOP/Shadowrocket-First/main/TalkatoneProxy.list

; 国外媒体
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

; Google 国际服务
ruleset=🌍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list

; 轻量代理规则
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 节点选择,clash-domain:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_proxy_domain.yaml,28800
ruleset=🚀 节点选择,clash-classic:https://raw.githubusercontent.com/shaufo/CCc/refs/heads/main/rule/custom_proxy_ip.yaml,28800

; 中国域名
ruleset=🎯 全球直连,[]GEOSITE,cn
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list

; 中国 IP
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve

;PT/BT 优化开启会使 80/443 以外端口的流量直连
;ruleset=🔀 非标端口,clash-classic:https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800

; 最终规则
ruleset=🐟 漏网之鱼,[]FINAL


;========================
; 策略组
;========================

; 主代理
custom_proxy_group=🚀 节点选择`select`[]波池加红杏`[]波池机场`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]美国自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; 国外媒体
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]波池机场`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]美国自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; Google
custom_proxy_group=🌍 Google`select`[]🚀 节点选择`[]香港自动`[]美国自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; GitHub
custom_proxy_group=🐙 GitHub`select`[]🚀 节点选择`[]FREE测速`[]香港自动`[]美国自动`[]台狮自动`[]欧洲自动`[]中东自动`[]南亚自动`[]日韩自动`[]♻️ 自动选择`[]DIRECT

; AI
custom_proxy_group=💬 AI平台`select`[]🚀 节点选择`[]香港自动`[]美国自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]波池加红杏`[]波池机场`[]红杏机场`[]♻️ 自动选择`[]DIRECT

; Telegram
custom_proxy_group=📲 电报信息`select`[]FREE测速`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT

;Talkatone
custom_proxy_group=📞 Talkatone`select`[]Talkatone节点`[]波池机场`[]香港自动`[]美国自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]DIRECT

; 微软
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; Apple
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; Google FCM
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; 全球直连
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; 广告拦截
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择

; 漏网之鱼
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择
;custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连

; 自动测速
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,50

;自定义节点
custom_proxy_group=波池加红杏`url-test`(波池1|波池2|红杏)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=波池机场`url-test`(波池1|波池2)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=红杏机场`url-test`(红杏)`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=一元机场`url-test`(一元)`http://www.gstatic.com/generate_204`60,,0
custom_proxy_group=FREE测速`url-test`(一元|CFnat|CF|MB)`http://www.gstatic.com/generate_204`60,,0
custom_proxy_group=Talkatone节点`url-test`^(?!.*(?:红杏|一元|MB|CF)).*(美国).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=香港自动`url-test`^(?!.*(?:一元|MB)).*(香港)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=美国自动`url-test`^(?!.*(?:一元|MB|CF|波池)).*(美国|加拿大).*`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=日韩自动`url-test`^(?!.*(?:一元|MB|CF)).*(日|日本|韩|韩国).*`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=台狮自动`url-test`^(?!.*(?:一元|MB|CF)).*(台|台湾|新|坡|新加坡|狮).*`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=欧洲自动`url-test`^(?!.*(?:一元|MB|CF)).*(英国|法国|德国|荷兰|瑞士|西班牙|瑞典|土耳其|希腊|挪威).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=中东自动`url-test`^(?!.*(?:一元|MB|CF)).*(印度|阿联酋|沙特阿拉伯|巴基斯坦|埃及|哈萨克斯坦|孟加拉国).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=南亚自动`url-test`^(?!.*(?:一元|MB|CF)).*(澳大利亚|越南|泰国|马来|菲律宾|缅甸|柬埔寨).*`http://www.gstatic.com/generate_204`300,,50
;========================
; 启用规则生成
;========================

enable_rule_generator=true
overwrite_original_rules=true
