; ############## 1. 策略组 ##############
; 主代理
custom_proxy_group=🚀 节点选择`select`[]波池加红杏`[]波池机场`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]美加自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; 国外媒体
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]波池机场`[]红杏机场`[]一元机场`[]FREE测速`[]香港自动`[]美加自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; Google
custom_proxy_group=🌍 Google`select`[]🚀 节点选择`[]香港自动`[]美加自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]♻️ 自动选择`[]DIRECT

; GitHub
custom_proxy_group=🐙 GitHub`select`[]🚀 节点选择`[]FREE测速`[]香港自动`[]美加自动`[]台狮自动`[]欧洲自动`[]中东自动`[]南亚自动`[]日韩自动`[]♻️ 自动选择`[]DIRECT

; AI
custom_proxy_group=💬 AI平台`select`[]🚀 节点选择`[]香港自动`[]美加自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]波池加红杏`[]波池机场`[]红杏机场`[]♻️ 自动选择`[]DIRECT

; Telegram
custom_proxy_group=📲 电报信息`select`[]FREE测速`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT

;Talkatone
custom_proxy_group=📞 Talkatone`select`[]Talkatone节点`[]波池机场`[]香港自动`[]美加自动`[]台狮自动`[]日韩自动`[]欧洲自动`[]中东自动`[]南亚自动`[]DIRECT

; 微软
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; Apple
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; Google FCM
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; 全球直连
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择

; 广告拦截
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择

; 漏网之鱼
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择
;custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连

; ############## 2. 节点组 ##############
custom_proxy_group=波池加红杏`url-test`(波池1|波池2|红杏)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=波池机场`url-test`(波池1|波池2)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=红杏机场`url-test`(红杏)`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=一元机场`url-test`(一元)`http://www.gstatic.com/generate_204`60,,0
custom_proxy_group=FREE测速`url-test`(一元|CFnat|CF|MB)`http://www.gstatic.com/generate_204`60,,0
custom_proxy_group=Talkatone节点`url-test`^(?!.*(?:红杏|一元|MB|CF)).*(美国).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=香港自动`url-test`^(?!.*(?:一元|MB)).*(香港)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=美加自动`url-test`^(?!.*(?:一元|MB|CF|波池)).*(美国|加拿大).*`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=日韩自动`url-test`^(?!.*(?:一元|MB|CF)).*(日|日本|韩|韩国).*`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=台狮自动`url-test`^(?!.*(?:一元|MB|CF)).*(台|台湾|新|坡|新加坡|狮).*`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=欧洲自动`url-test`^(?!.*(?:一元|MB|CF)).*(英国|法国|德国|荷兰|瑞士|西班牙|瑞典|土耳其|希腊|挪威).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=中东自动`url-test`^(?!.*(?:一元|MB|CF)).*(印度|阿联酋|沙特阿拉伯|巴基斯坦|埃及|哈萨克斯坦|孟加拉国).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=南亚自动`url-test`^(?!.*(?:一元|MB|CF)).*(澳大利亚|越南|泰国|马来|菲律宾|缅甸|柬埔寨).*`http://www.gstatic.com/generate_204`300,,50

; ############## 3. 规则集 ##############
; 局域网
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
; Apple
ruleset=Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
; 🎯 全球直连 Google 白名单
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
; AI
ruleset=AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
; 微软
ruleset=微软Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=微软云盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
; Google
ruleset=Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
; YouTube
ruleset=YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
; GitHub
ruleset=GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
; Telegram
ruleset=Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
; Talkatone
ruleset=Talkatone,https://raw.githubusercontent.com/LOWERTOP/Shadowrocket-First/main/TalkatoneProxy.list
; 京东
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/JingDong/JingDong.list
; 中国 IP
ruleset=🎯 全球直连,[]GEOIP,CN
; 最终规则
ruleset=漏网之鱼,[]FINAL

; ############## 4. 功能配置 ##############
enable_rule_generator=true
overwrite_original_rules=true
